name: Rstudio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.73049
title: Radiance Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#f39c11'
    - '#000000'
    - '#5e5e5e'
    - '#a6a6a6'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
