name: Rstudio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.3957447
title: Radiance Studio
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#000000'
    - '#F98E00'
    - '#FDC77F'
    - '#7F8181'
  brandStrength: 0
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
